# Source: https://github.com/Lectem/TravisCI-for-devkitPro/blob/master/devkitARM-latestctrulib.travis.yml
language: c

notifications:
  email: false

before_install:
  - wget http://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitARMupdate.pl
  - export DEVKITPRO=/home/travis/devkitPro
  - export DEVKITARM=${DEVKITPRO}/devkitARM
  - git clone https://github.com/smealum/ctrulib.git

install:
  - sudo perl devkitARMupdate.pl
  - cd ctrulib/libctru 
  - make
  - cd ..
  - sudo cp -rf libctru/ ${DEVKITPRO}
  - cd ..
script:
  - make

# Source: https://github.com/k3rn31p4nic/travis-ci-discord-webhook
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
